[tool.poetry]
name = "cotoba-cli"
version = "0.2.1"
description = ""
authors = []
exclude = ["integration_tests", "run_integration_test.sh"]

[tool.poetry.scripts]
cotoba = "cotoba_cli.cli:cli_root"

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.9"
requests = "^2.21"
click = "^7.0"
toml = "^0"
pytz = "^2019"
python-jose = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
pytest-cov = "^2.6"
flake8 = "^3.7"
freezegun = "^0"
pep8-naming = "^0"
pytest-mock = "^1.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
